package action

const (
	AttachCapabilitySets        = "Attach Capability Sets"
	BuildAndPushUi              = "Build and push UI"
	BuildSystem                 = "Build System"
	CheckPorts                  = "Check Ports"
	CreateConsortiums           = "Create Consortiums"
	CreateRoles                 = "Create Roles"
	CreateTenantEntitlements    = "Create Tenant Entitlements"
	CreateTenants               = "Create Tenants"
	CreateUsers                 = "Create Users"
	DeployAdditionalSystem      = "Deploy Additional System"
	DeployApplication           = "Deploy Application"
	DeployManagement            = "Deploy Management"
	DeployModule                = "Deploy Module"
	DeployModules               = "Deploy Modules"
	DeploySystem                = "Deploy System"
	DeployUi                    = "Deploy UI"
	DetachCapabilitySets        = "Detach Capability Sets"
	GetEdgeApiKey               = "Get Edge Api Key"          //nolint:gosec // G101: Not a hardcoded credential, just an action name
	GetKeycloakAccessToken      = "Get Keycloak Access Token" //nolint:gosec // G101: Not a hardcoded credential, just an action name
	GetVaultRootToken           = "Get Vault Root Token"      //nolint:gosec // G101: Not a hardcoded credential, just an action name
	InterceptModule             = "Intercept Module"
	ListModules                 = "List Modules"
	ListModuleVersions          = "List Module Versions"
	ListSystem                  = "List System"
	PurgeTenants                = "Purge Tenants"
	ReindexIndices              = "Reindex Indices"
	RemoveRoles                 = "Remove Roles"
	RemoveTenantEntitlements    = "Remove Tenant Entitlements"
	RemoveTenants               = "Remove Tenants"
	RemoveUsers                 = "Remove Users"
	Root                        = "Root"
	UndeployAdditionalSystem    = "Undeploy Additional System"
	UndeployApplication         = "Undeploy Application"
	UndeployManagement          = "Undeploy Management"
	UndeployModule              = "Undeploy Module"
	UndeployModules             = "Undeploy Modules"
	UndeploySystem              = "Undeploy System"
	UndeployUi                  = "Undeploy UI"
	UpdateKeycloakPublicClients = "Update Keycloak Public Clients"
	UpdateModuleDiscovery       = "Update Module Discovery"
)
