networks:
  eureka-net:
    name: eureka
    external: true
  
services:
  mod-orders-sc:
    container_name: eureka-custom-mod-orders-sc
    hostname: mod-orders-sc
    image: folioci/folio-module-sidecar:$SIDECAR_VERSION
    restart: on-failure
    networks: 
      - eureka-net
    ports:
      - 37001:8081
    environment:
      SC_LOG_LEVEL: INFO
      ROOT_LOG_LEVEL: INFO
      QUARKUS_HTTP_LIMITS_MAX_INITIAL_LINE_LENGTH: 8192
      SIDECAR_FORWARD_UNKNOWN_REQUESTS_DESTINATION: http://kong-local.eureka:8000
      REQUEST_TIMEOUT: 604800000
      MOD_USERS_KEYCLOAK_URL: http://mod-users-keycloak-sc.eureka:8081
      SIDECAR_FORWARD_UNKNOWN_REQUESTS: true
      SIDECAR: true
      KC_URI_VALIDATION_ENABLED: false
      ALLOW_CROSS_TENANT_REQUESTS: true
      MOD_USERS_BL: http://mod-users-bl-sc.eureka:8081
      JAVA_OPTIONS: >-
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 
        -XX:MaxRAMPercentage=80.0 -Xms128m -Xmx400m 
        -Djdk.internal.httpclient.disableHostnameVerification=true
      KC_URL: http://keycloak.eureka:8080
      KC_ADMIN_CLIENT_ID: supersecret
      KC_SERVICE_CLIENT_ID: sidecar-module-access-client
      KC_LOGIN_CLIENT_SUFFIX: -application
      SECRET_STORE_TYPE: VAULT
      SECRET_STORE_VAULT_TOKEN: $VAULT_ROOT_TOKEN
      SECRET_STORE_VAULT_ADDRESS: http://vault.eureka:8200
      TM_CLIENT_URL: http://mgr-tenants.eureka:8081
      AM_CLIENT_URL: http://mgr-applications.eureka:8081
      TE_CLIENT_URL: http://mgr-tenant-entitlements.eureka:8081
      MODULE_NAME: mod-orders
      MODULE_VERSION: $MOD_ORDERS_VERSION
      MODULE_URL: $MOD_ORDERS_URL
      SIDECAR_NAME: mod-orders-sc
      SIDECAR_URL: http://mod-orders-sc.eureka:8081
  
  mod-finance-sc:
    container_name: eureka-custom-mod-finance-sc
    hostname: mod-finance-sc
    image: folioci/folio-module-sidecar:$SIDECAR_VERSION
    restart: on-failure
    networks: 
      - eureka-net
    ports:
      - 37002:8081
    environment:
      SC_LOG_LEVEL: INFO
      ROOT_LOG_LEVEL: INFO
      QUARKUS_HTTP_LIMITS_MAX_INITIAL_LINE_LENGTH: 8192
      SIDECAR_FORWARD_UNKNOWN_REQUESTS_DESTINATION: http://kong-local.eureka:8000
      REQUEST_TIMEOUT: 604800000
      MOD_USERS_KEYCLOAK_URL: http://mod-users-keycloak-sc.eureka:8081
      SIDECAR_FORWARD_UNKNOWN_REQUESTS: true
      SIDECAR: true
      KC_URI_VALIDATION_ENABLED: false
      ALLOW_CROSS_TENANT_REQUESTS: true
      MOD_USERS_BL: http://mod-users-bl-sc.eureka:8081
      JAVA_OPTIONS: >-
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 
        -XX:MaxRAMPercentage=80.0 -Xms128m -Xmx400m 
        -Djdk.internal.httpclient.disableHostnameVerification=true
      KC_URL: http://keycloak.eureka:8080
      KC_ADMIN_CLIENT_ID: supersecret
      KC_SERVICE_CLIENT_ID: sidecar-module-access-client
      KC_LOGIN_CLIENT_SUFFIX: -application
      SECRET_STORE_TYPE: VAULT
      SECRET_STORE_VAULT_TOKEN: $VAULT_ROOT_TOKEN
      SECRET_STORE_VAULT_ADDRESS: http://vault.eureka:8200
      TM_CLIENT_URL: http://mgr-tenants.eureka:8081
      AM_CLIENT_URL: http://mgr-applications.eureka:8081
      TE_CLIENT_URL: http://mgr-tenant-entitlements.eureka:8081
      MODULE_NAME: mod-finance
      MODULE_VERSION: $MOD_FINANCE_VERSION
      MODULE_URL: $MOD_FINANCE_URL
      SIDECAR_NAME: mod-finance-sc
      SIDECAR_URL: http://mod-finance-sc.eureka:8081