# Profile
profile:
  name: minimal
# Application
application:
  name: app-minimal
  version: 1.0.0
  platform: base
  fetch-descriptors: false
  port-start: 30000
# Registry
registry:
  registry-url: https://folio-registry.dev.folio.org
  folio-install-json-url: https://raw.githubusercontent.com/folio-org/platform-complete/snapshot/install.json
  eureka-install-json-url: https://raw.githubusercontent.com/folio-org/platform-complete/snapshot/eureka-platform.json
  namespaces:
    platform-complete-ui: bkadirkhodjaev
# Environment
environment:
  # General
  ENV: folio
  # PostgreSQL
  DB_HOST: postgres.eureka
  DB_PORT: 5432
  DB_DATABASE: folio
  DB_USERNAME: folio_rw
  DB_PASSWORD: supersecret
  # Kafka
  KAFKA_HOST: kafka.eureka
  KAFKA_PORT: 9092
  # Elasticsearch
  ELASTICSEARCH_URL: http://host.docker.internal:9200
  # AWS S3/MinIO
  AWS_URL: http://host.docker.internal:9000
  AWS_REGION: us-east-1
  AWS_BUCKET: example-bucket
  AWS_ACCESS_KEY_ID: minioadmin
  AWS_SECRET_ACCESS_KEY: minioadmin
  S3_IS_AWS: false
  S3_URL: http://host.docker.internal:9000
  S3_REGION: us-east-1
  S3_ACCESS_KEY_ID: minioadmin
  S3_SECRET_ACCESS_KEY: minioadmin
  S3_BUCKET: example-bucket
  SPLIT_FILES_ENABLED: true
  # Consortia
  SYSTEM_USER_PASSWORD: system_user_password
  # Management
  MT_URL: http://mgr-tenants.eureka:8081
  AM_CLIENT_URL: http://mgr-applications.eureka:8081
  KONG_ADMIN_URL: http://api-gateway.eureka:8001
  # Keycloak
  KC_URL: http://keycloak.eureka:8080
  KC_CONFIG_TTL: 3600s
  KC_ADMIN_CLIENT_ID: supersecret
  KC_ADMIN_USERNAME: admin
  KC_ADMIN_PASSWORD: admin
  SECURITY_ENABLED: false
  KC_IMPORT_ENABLED: true
  KC_INTEGRATION_ENABLED: true
  KC_LOGIN_CLIENT_SUFFIX: -application
  KC_SERVICE_CLIENT_ID: sidecar-module-access-client
  KONG_INTEGRATION_ENABLED: true
  OKAPI_INTEGRATION_ENABLED: false
  WEB_CLIENT_TLS_VERIFY_HOSTNAME: false
  # Java
  JAVA_OPTIONS: |
    -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 
    -XX:MaxRAMPercentage=70.0 -Xms128m -Xmx400m 
    -Djdk.internal.httpclient.disableHostnameVerification=true"
# Tenants
tenants:
  diku:
    deploy-ui: true
# Roles
roles:
  Admin:
    tenant: diku
    capability-sets:
      - all
  User:
    tenant: diku
    capability-sets: []
# Users
users:
  diku_admin:
    tenant: diku
    password: admin
    last-name: John
    first-name: Doe
    roles:
      - Admin
      - User
  diku_user:
    tenant: diku
    password: user
    last-name: John
    first-name: Smith
    roles:
      - User
# Sidecar module
sidecar-module:
  image: folio-module-sidecar
  environment:
    SIDECAR: true
    SC_LOG_LEVEL: DEBUG
    ROOT_LOG_LEVEL: DEBUG
    REQUEST_TIMEOUT: 604800000
    KC_URI_VALIDATION_ENABLED: false
    ALLOW_CROSS_TENANT_REQUESTS: true
    SIDECAR_FORWARD_UNKNOWN_REQUESTS: true
    QUARKUS_HTTP_LIMITS_MAX_INITIAL_LINE_LENGTH: 8192
    MOD_USERS_BL: http://mod-users-bl.eureka:8081
    MOD_USERS_KEYCLOAK_URL: http://mod-users-keycloak.eureka:8081
    SIDECAR_FORWARD_UNKNOWN_REQUESTS_DESTINATION: http://api-gateway.eureka:8000
    JAVA_OPTIONS: |
      -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      -XX:+UseZGC -XX:MaxRAMPercentage=85.0 -Xms50m -Xmx128m
      -Dquarkus.http.host=0.0.0.0 -Dquarkus.log.level=DEBUG -Dquarkus.log.category.'org.apache.kafka'.level=DEBUG 
      -Djava.util.logging.manager=org.jboss.logmanager.LogManager
# Backend modules
backend-modules:
  # Management modules
  mgr-applications:
    port: 9901
    environment:
      # DB
      DB_DATABASE: mgr_applications
      DB_USERNAME: mgr_applications_rw
      DB_PASSWORD: supersecret
      # Management
      MODULE_URL: http://mgr-applications.eureka:8081
      TE_URL: http://mgr-tenant-entitlements.eureka:8081
      VALIDATION_MODE: none
  mgr-tenants:
    port: 9902
    environment:
      # DB
      DB_DATABASE: mgr_tenant
      DB_USERNAME: mgr_tenant_rw
      DB_PASSWORD: supersecret
      # Management
      MODULE_URL: http://mgr-tenants.eureka:8081
      CACHE_EXPIRATION_TTL: 55s
  mgr-tenant-entitlements:
    version: 2.0.2
    port: 9903
    environment:
      # DB
      DB_DATABASE: mgr_tenant_entitlements
      DB_USERNAME: mgr_tenant_entitlements_rw
      DB_PASSWORD: supersecret
      # Management
      MODULE_URL: http://mgr-tenant-entitlements.eureka:8081
      TENANT_URL: http://mgr-tenants.eureka:8081
      AM_CLIENT_URL: http://mgr-applications.eureka:8081
      VALIDATION_INTERFACE_INTEGRITY_ENABLED: 'false'
      FOLIO_CLIENT_CONNECT_TIMEOUT: 60s
      FOLIO_CLIENT_READ_TIMEOUT: 180s
      FLOW_ENGINE_THREADS_NUM: '1'
      RETRIES_MODULE_MAX: '10'
  # Keycloak modules
  mod-users-keycloak:
    port: 9904
    sidecar: true
    environment:
      OKAPI_URL: http://mod-users-keycloak-sc.eureka:8081
      INCLUDE_ONLY_VISIBLE_PERMISSIONS: 'false'
      MOD_USERS_URL: http://mod-users.eureka
      FOLIO_SYSTEM_USER_ENABLED: 'false'
      SYSTEM_USER_CREATE: 'false'
      SYSTEM_USER_ENABLED: 'false'
      SYSTEM_USER_NAME: mod-users-keycloak
      SYSTEM_USER_USERNAME: mod-users-keycloak
  mod-login-keycloak:
    port: 9905
    sidecar: true
    environment:
      X_OKAPI_TOKEN_HEADER_ENABLED: 'true'
  mod-roles-keycloak:
    port: 9906
    sidecar: true
  mod-scheduler:
    port: 9907
    sidecar: true
    environment:
      FOLIO_SYSTEM_USER_ENABLED: 'false'
      SYSTEM_USER_CREATE: 'false'
      SYSTEM_USER_ENABLED: 'false'
      SYSTEM_USER_NAME: mod-scheduler
      SYSTEM_USER_USERNAME: mod-scheduler
  # Keycloak Consortia modules
  mod-consortia-keycloak:
    deploy-module: false
    port: 9908
    sidecar: true
    environment:
      FOLIO_SYSTEM_USER_ENABLED: 'false'
      SYSTEM_USER_CREATE: 'false'
      SYSTEM_USER_ENABLED: 'false'
      SYSTEM_USER_NAME: mod-consortia-keycloak
      SYSTEM_USER_USERNAME: mod-consortia-keycloak
  # Core Modules
  mod-permissions:
  mod-configuration:
  mod-users:
  mod-users-bl:
  mod-roles:
  mod-password-validator:
  mod-settings:
  mod-notes:
  mod-tags:
# Frontend modules
frontend-modules:
  folio_developer:
  folio_stripes-core:
  folio_notes:
  folio_tags:
  folio_stripes-smart-components:
  folio_plugin-find-authority:
# Custom Frontend modules
custom-frontend-modules:
  folio_authorization-roles:
    version: 1.6.10990000000025
  folio_authorization-policies:
    version: 1.3.10990000000015
  folio_plugin-select-application:
    version: 1.1.1099000000003
