# Storage type
secureStore.type=Ephemeral

# Tenants
tenants=diku,testedgeorders,testedgeorders1,testedgeorders2,testedgeorders3,testedgeorders4,testedgeorders5,testedgeorders6,testedgeorders7,testedgeorders8,testedgeorders9,testedgeorders10

# Tenant users
diku=diku_admin,admin
testedgeorders=test-user,Ab7@Kx9!FipsAlphaBravo#Zr3Qp!Xt
testedgeorders1=test-user,Ab7@Kx9!FipsAlphaBravo#Zr3Qp!Xt
testedgeorders2=test-user,Ab7@Kx9!FipsAlphaBravo#Zr3Qp!Xt
testedgeorders3=test-user,Ab7@Kx9!FipsAlphaBravo#Zr3Qp!Xt
testedgeorders4=test-user,Ab7@Kx9!FipsAlphaBravo#Zr3Qp!Xt
testedgeorders5=test-user,Ab7@Kx9!FipsAlphaBravo#Zr3Qp!Xt
testedgeorders6=test-user,Ab7@Kx9!FipsAlphaBravo#Zr3Qp!Xt
testedgeorders7=test-user,Ab7@Kx9!FipsAlphaBravo#Zr3Qp!Xt
testedgeorders8=test-user,Ab7@Kx9!FipsAlphaBravo#Zr3Qp!Xt
testedgeorders9=test-user,Ab7@Kx9!FipsAlphaBravo#Zr3Qp!Xt
testedgeorders10=test-user,Ab7@Kx9!FipsAlphaBravo#Zr3Qp!Xt
