FROM node:20
WORKDIR /app

# Dynamically pull the requested target workspace
RUN git clone -b {{.Branch}} {{.URL}} .

ENV HUSKY=0
ENV NODE_OPTIONS=--max-old-space-size=4096

RUN npm install --legacy-peer-deps
EXPOSE 3000

CMD ["npm", "run", "{{.StartScript}}", "--", "--host", "0.0.0.0"]